% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={記述統計},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{記述統計}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\hypertarget{descriptive-statistics}{%
\paragraph{descriptive statistics}\label{descriptive-statistics}}

\hypertarget{ux5ea6ux6570ux5206ux5e03ux8868}{%
\paragraph{度数分布表}\label{ux5ea6ux6570ux5206ux5e03ux8868}}

\begin{itemize}
\item
  度数分布表とは?

  \begin{itemize}
  \tightlist
  \item
    data を \textbf{階級} に分けて階級ごとの \textbf{度数} を数えた表
  \end{itemize}
\end{itemize}

\hypertarget{histogram}{%
\paragraph{histogram}\label{histogram}}

\begin{itemize}
\item
  度数分布表から縦軸に \textbf{度数} 横軸に \textbf{階級} をとり
  \textbf{グラフ化} したもの

  \begin{itemize}
  \tightlist
  \item
    集団の特徴を定義付けていく
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{height }\OtherTok{=}
  \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{167}\NormalTok{, }\DecValTok{5}\NormalTok{)}
\NormalTok{y }\OtherTok{=} \FunctionTok{hist}\NormalTok{(height)}
\end{Highlighting}
\end{Shaded}

\includegraphics{descriptive_files/figure-latex/unnamed-chunk-1-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{y}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $breaks
##  [1] 156 158 160 162 164 166 168 170 172 174 176 178 180
## 
## $counts
##  [1]  1  4  3 14 16 15 13 14 10  5  1  4
## 
## $density
##  [1] 0.005 0.020 0.015 0.070 0.080 0.075 0.065 0.070 0.050 0.025 0.005 0.020
## 
## $mids
##  [1] 157 159 161 163 165 167 169 171 173 175 177 179
## 
## $xname
## [1] "height"
## 
## $equidist
## [1] TRUE
## 
## attr(,"class")
## [1] "histogram"
\end{verbatim}

\hypertarget{ux57faux672cux7d71ux8a08ux91cf}{%
\subsubsection{基本統計量}\label{ux57faux672cux7d71ux8a08ux91cf}}

　分布の基本的な特性を数値で表した指標

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{itemize}
\tightlist
\item
  \textbf{代表値} (分布の中心を表す指標)

  \begin{itemize}
  \tightlist
  \item
    \emph{平均} : (算術平均, 幾何平均, 調和平均, 加重平均)
  \item
    \emph{中央値(メジアン)}
  \item
    \emph{最頻値(モード)}
  \end{itemize}
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{itemize}
\tightlist
\item
  \textbf{散布度} (分布のばらつきを表す指標)

  \begin{itemize}
  \tightlist
  \item
    \emph{範囲(レンジ)}
  \item
    \emph{四分位範囲}
  \item
    \emph{平均偏差}
  \item
    \textbf{分散}
  \item
    \textbf{標準偏差}
  \item
    \emph{変動係数}
  \item
    \emph{標準化得点}
  \end{itemize}
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{ux7b97ux8853ux5e73ux5747}{%
\subsubsection{算術平均}\label{ux7b97ux8853ux5e73ux5747}}

　中心を表す指標

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{itemize}
\item
  全ての data を足して個数で割った値　=　\textbf{平均}　=　\(\mu\)

  \begin{itemize}
  \tightlist
  \item
    \textbf{長所}

    \begin{itemize}
    \tightlist
    \item
      一般的, 計算が簡単, 数値の意味の理解のし易さ
    \end{itemize}
  \item
    \textbf{短所}

    \begin{itemize}
    \tightlist
    \item
      外れ値の影響を受けやすい, 分布の形状に依存する
    \end{itemize}
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{=} \FunctionTok{as.integer}\NormalTok{(height)}
\FunctionTok{hist}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\includegraphics{descriptive_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 167.4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{median}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 167
\end{verbatim}

\begin{itemize}
\item
  \textbf{平均} : 167.4 cm　\textbar{}　\textbf{中央値} : 167 cm

  \begin{itemize}
  \tightlist
  \item
    解析する histograme の形を考慮して \texttt{mean(\ )},
    \texttt{median(\ )} を使い分けていく
  \end{itemize}
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{itemize}
\item
  \textbf{summary( )} : 一度に様々な数値を取得できる

  \begin{itemize}
  \tightlist
  \item
    Min : 最小　\textbar{}　1st : 25\%　\textbar{}　Median :
    中央値　\textbar{}　Mean : 平均　\textbar{}　3rd :
    75\%　\textbar{}　Max : 最大値
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   157.0   164.0   167.0   167.4   171.0   179.0
\end{verbatim}

\hypertarget{ux5206ux6563ux6a19ux6e96ux504fux5dee}{%
\subsubsection{分散・標準偏差}\label{ux5206ux6563ux6a19ux6e96ux504fux5dee}}

　ばらつきを表す指標

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{itemize}
\item
  平均との差の二乗平均を求めた値　\textbf{分散}(\(\sigma^2\))　その平方根　\textbf{標準偏差}(\(\sigma\))

  \begin{itemize}
  \tightlist
  \item
    \textbf{長所}

    \begin{itemize}
    \tightlist
    \item
      バラつきの数値で最も一般的, 理論的に扱いやすい
    \end{itemize}
  \item
    \textbf{短所}

    \begin{itemize}
    \tightlist
    \item
      分散は単位が分かりづらい
    \end{itemize}
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\includegraphics{descriptive_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 23.15152
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.811602
\end{verbatim}

\begin{itemize}
\item
  \textbf{分散} : 23.1515152　\textbar{}　\textbf{標準偏差} : 4.8116021

  \begin{itemize}
  \tightlist
  \item
    ※ R言語の分散は \textbf{不偏分散} なので注意!
  \end{itemize}
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{ux6a19ux6e96ux5316}{%
\subsubsection{標準化}\label{ux6a19ux6e96ux5316}}

　data の　\textbf{平均値を 0 , 分散を 1}　に変換する操作

\[
\frac{X - \mu}{\sigma}
\]

（それぞれの値　-　平均）　÷　標準偏差　=　標準化 ↓

標準化により異なる集団も全て　標準得点　で比較できる

\textbar\textbar{} scale を合わせて比較することが出来る

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   [1] 171 165 179 178 163 171 162 163 173 157 169 168 167 162 169 171 172 160
##  [19] 163 164 165 174 168 163 158 160 169 167 167 163 172 172 164 170 164 166
##  [37] 166 164 165 162 168 165 168 171 164 167 165 170 167 163 174 159 158 179
##  [55] 167 178 162 171 164 171 170 172 166 173 163 170 171 174 173 163 173 174
##  [73] 162 169 167 161 166 170 164 168 168 170 168 167 158 168 172 175 164 165
##  [91] 166 176 168 167 164 166 173 165 163 171
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(}\FunctionTok{scale}\NormalTok{(x))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            [,1]
## [1,]  0.7481915
## [2,] -0.4987944
## [3,]  2.4108394
## [4,]  2.2030084
## [5,] -0.9144563
## [6,]  0.7481915
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var}\NormalTok{(}\FunctionTok{scale}\NormalTok{(x))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1]
## [1,]    1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(}\FunctionTok{scale}\NormalTok{(x))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.186709e-15
\end{verbatim}

\begin{itemize}
\item
  \textbf{標準化} : scale( )

  \begin{itemize}
  \item
    標準化後の \textbf{分散} : 1
  \item
    標準化後の \textbf{平均} : \ensuremath{-1.1867086\times 10^{-15}}
  \end{itemize}
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{ux6b63ux898fux5206ux5e03}{%
\subsubsection{正規分布}\label{ux6b63ux898fux5206ux5e03}}

　左右対称つり鐘型をした　\textbf{確率分布}　多くの現象がこの分布に従う
　\\
　 → 身長, 植物の大きさ, testの点数, 工業製品の誤差 etc\ldots{}

\begin{itemize}
\item
  \textbf{確率分布}

  \begin{itemize}
  \item
    グラフの　\textbf{面積が確率}　なるようなグラフ

    \begin{itemize}
    \item
      全部足すと \textbf{1} になる =　\textbf{確率 100\%}
    \item
      \texttt{平均値}　と　\texttt{標準偏差}　で形が決まる
    \item
      \emph{数学的に一意に決まるグラフ}
    \end{itemize}
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(x, }\AttributeTok{breaks =} \FunctionTok{seq}\NormalTok{(}\DecValTok{150}\NormalTok{, }\DecValTok{180}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{descriptive_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(x)}
\NormalTok{s }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(x)}
\NormalTok{x1 }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\DecValTok{150}\NormalTok{, }\DecValTok{180}\NormalTok{, }\FloatTok{0.01}\NormalTok{)}
\NormalTok{d }\OtherTok{=} \FunctionTok{dnorm}\NormalTok{(x1, }\AttributeTok{mean =}\NormalTok{ m, }\AttributeTok{sd =}\NormalTok{ s)}
\FunctionTok{plot}\NormalTok{(x1, d, }\AttributeTok{type =} \StringTok{"l"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{descriptive_files/figure-latex/unnamed-chunk-6-2.pdf} -
\textbf{平均} : 167.4 cm　\textbar{}　\textbf{標準偏差} : 4.8116021

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{ux6b63ux898fux5206ux5e03ux304bux3089ux5206ux304bux308bux3053ux3068}{%
\subsubsection{正規分布から分かること}\label{ux6b63ux898fux5206ux5e03ux304bux3089ux5206ux304bux308bux3053ux3068}}

　分布のある範囲に　\textbf{どれだけのdataが含まれているか}　が分かる 　

面積が分かるという事は \textbar\textbar{}

その範囲に入る dataの確率 が分かる

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X1 }\OtherTok{\textless{}{-}} \DecValTok{850}
\NormalTok{m1 }\OtherTok{\textless{}{-}} \FloatTok{582.6}
\NormalTok{s1 }\OtherTok{\textless{}{-}} \FloatTok{172.7}
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{as.integer}\NormalTok{(}\DecValTok{103955}\NormalTok{)}
\NormalTok{Z }\OtherTok{=}\NormalTok{ (X1 }\SpecialCharTok{{-}}\NormalTok{ m1)}\SpecialCharTok{/}\NormalTok{s1}
\end{Highlighting}
\end{Shaded}

\textbf{自分の得点} : \(X\) = 850　\textbar{}　\textbf{平均点} \(\mu\) :
582.6　\textbar{}　\textbf{標準偏差} \(\sigma\) :
172.7　\textbar{}　\textbf{標準化} :
1.5483497　\textbar{}　\textbf{総数(人)} : 103955

\hypertarget{ux6a19ux6e96ux5316-1}{%
\paragraph{標準化}\label{ux6a19ux6e96ux5316-1}}

\[
Z = \frac{得点 - 平均値}{標準偏差}
\]

\hypertarget{ux516cux5f0f}{%
\paragraph{公式}\label{ux516cux5f0f}}

\[
Z = \frac{X - \mu}{\sigma} = \frac{850 - 582.6}{172.7} \simeq 1.55
\]

\hypertarget{ux6b63ux898fux5206ux5e03ux306eux9762ux7a4dux3092ux6c42ux3081ux308b}{%
\paragraph{正規分布の面積を求める}\label{ux6b63ux898fux5206ux5e03ux306eux9762ux7a4dux3092ux6c42ux3081ux308b}}

\begin{itemize}
\item
  Rの場合 pnorm( )では,　\textbf{無限大の -}
  (マイナス)方向から　\textbf{1.55}　までを求める

  \begin{itemize}
  \tightlist
  \item
    なので　\textbf{- 0.5}　で 0 から ー 方向の面積を引く
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d1 }\OtherTok{=} \FunctionTok{pnorm}\NormalTok{(Z, }\AttributeTok{mean =} \DecValTok{0}\NormalTok{, }\AttributeTok{sd =} \DecValTok{1}\NormalTok{)}
\NormalTok{d1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9392309
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d2 }\OtherTok{=} \FunctionTok{pnorm}\NormalTok{(Z, }\AttributeTok{mean =} \DecValTok{0}\NormalTok{, }\AttributeTok{sd =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{{-}} \FloatTok{0.5}
\NormalTok{d2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4392309
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{N }\OtherTok{=} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ d1}
\NormalTok{N}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.06076906
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{N1 }\OtherTok{=} \FunctionTok{as.integer}\NormalTok{(n}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ d1)}\SpecialCharTok{*}\DecValTok{100}\NormalTok{)}
\NormalTok{N1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 631724
\end{verbatim}

\begin{itemize}
\item
  \textbf{無限大の -} (マイナス)方向から　\textbf{1.55}　までの面積 :
  0.9392309
\item
  \textbf{- 0.5}　で 0 から ー 方向の面積を引く : 0.4392309
\item
  \textbf{上位の面積} :　0.0607691　\textbar{}　\textbf{上位からの順位}
  : 631724
\end{itemize}

\end{document}
